# Generated by Django 2.0.3 on 2018-03-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='steps_reproduce',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='tickets',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee_staff', to='bugfixer.Staff'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_staff', to='bugfixer.Staff'),
        ),
    ]
