# Generated by Django 2.0.3 on 2018-03-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0002_auto_20180324_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='tickets_url',
        ),
    ]
