# Generated by Django 2.0.3 on 2018-03-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0003_remove_tickets_tickets_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
