# Generated by Django 2.0.3 on 2018-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0004_auto_20180324_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ON', 'OPEN'), ('IS', 'IN PROGRESS'), ('RW', 'REVIEW'), ('CD', 'CLOSED')], max_length=2),
        ),
    ]
