# Generated by Django 2.0.3 on 2018-03-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0005_auto_20180324_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee_staff', to='bugfixer.Staff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_staff', to='bugfixer.Staff'),
        ),
    ]
