# Generated by Django 2.0.3 on 2018-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0012_auto_20180404_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='num_of_ppl_affected',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('REVIEW', 'REVIEW'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=30),
        ),
    ]
