# Generated by Django 2.0.3 on 2018-04-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0015_auto_20180418_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
