# Generated by Django 2.0.3 on 2018-04-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0019_auto_20180419_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
