# Generated by Django 2.0.3 on 2018-05-09 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfixer', '0021_auto_20180509_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_staff', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
